### ISSUE TITLE
Bug with Cnn14-T state loading

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [autrainer/autrainer#66]
# Description

Loading the pretrained weights of `Cnn14-32k` causes an `UnpicklingError` with the report shown below. Seems to be caused by recent changes to `torch` requiring the provision of `weights_only=True` argument when using `torch.load`.

However, the offending line (see below) already seems to account for this:

```python
with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=UserWarning)
        model.load_state_dict(
            torch.load(
                weights_path,
                map_location="cpu",
                weights_only=True,
            )["model"],
            strict=False,
        )
```

# Bug report

```bash
❯ HYDRA_FULL_ERROR=1 autrainer train dataset=ToyImage-C model=Cnn14-16k-T
[2024-11-28 11:17:52,343][HYDRA] Launching 1 jobs locally
[2024-11-28 11:17:52,344][HYDRA]        #0 : +seed=1 +batch_size=32 +learning_rate=0.001 dataset=ToyImage-C model=Cnn14-16k-T optimizer=Adam
[2024-11-28 11:17:56,203][root][WARNING] - Device 'cuda:0' is not available. Falling back to CPU.
/nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/sh: line 1: pip: command not found
Error executing job with overrides: ['+seed=1', '+batch_size=32', '+learning_rate=0.001', 'dataset=ToyImage-C', 'model=Cnn14-16k-T', 'optimizer=Adam']
Traceback (most recent call last):
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/models/cnn_14.py", line 47, in __init__
    load_transfer_weights(self, self.transfer)
  File "/home/trianand/local-work/thesis/autrainer/autrainer/models/utils.py", line 38, in load_transfer_weights
    torch.load(
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/serialization.py", line 1383, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
        (1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
        (2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
        WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([_reconstruct])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/bin/autrainer", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/cli.py", line 108, in main
    cli.main()
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/cli.py", line 100, in main
    command.run(args, unknown)
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/abstract_script.py", line 68, in run
    self.main(args)
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/train_script.py", line 75, in main
    main()
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
            ^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 181, in sweep
    _ = r.return_value
        ^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/train_script.py", line 69, in main
    trainer = ModularTaskTrainer(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/training/training.py", line 141, in __init__
    self.model = autrainer.instantiate(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/wrappers/instantiate.py", line 80, in instantiate
    obj = hydra.utils.instantiate(config, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'autrainer.models.cnn_14.Cnn14':
UnpicklingError('Weights only load failed. This file can still be loaded, to do so you have two options, \x1b[1mdo those steps only if you trust the source of the checkpoint\x1b[0m. \n\t(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.\n\t(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.\n\tWeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([_reconstruct])` to allowlist this global if you trust this class/function.\n\nCheck the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.')
```

# Steps to reproduce

Run `autrainer train dataset=ToyImage-C model=Cnn14-16k-T` on the current `master` (and all branches)

Running `autrainer train dataset=ToyImage-C model=Cnn14-32k-T` on the current `master` (and all branches) should reproduce the bug, but it doens't. I am investigating.

First reported by @Marius-Moldo

**Comment by ATriantafyllopoulos** [comment]
More info, I have tried to manually load the weights, and it seems like the error is caused by `weights_only=True`. The model loads without it, but I think we should stick with `weights_only=True` as the safer option and find a workaround for this particular model

**Comment by ramppdev** [comment]
Just for clarity, which torch version was this on?

**Comment by ATriantafyllopoulos** [comment]
> Just for clarity, which torch version was this on?

`v2.5.0` (for me)
