### ISSUE TITLE
openSMILE functionals

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [autrainer/autrainer#72]
I recently came across a problem that when extracting new functionals with `openSMILE` in the `feature/format-datasets` branch.

The issue is that data is loaded in the format `(channels, samples)`, which is then converted to `(1, num_features)` (`openSMILE` only works in `mono` anyway). 

When loaded, and put to a batch of dimension N, this results in a tensor of `(N, num_features, 1)`, which is then passed to an `FFNN` (in the typical case), but causes the forward function to crash because of this extra `1` dimension. 
This happens during the call to `summary`,

Here's a representative error message:

```python
Error executing job with overrides: ['+seed=1', '+batch_size=4', '+learning_rate=0.0001', 'inference_batch_size=1', 'dataset=COPD-ComParE-func', 'model=FFNN-IS16', 'optimizer=Adam']
Traceback (most recent call last):
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torchinfo/torchinfo.py", line 295, in forward_pass
    _ = model(*x, **kwargs)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
    return inner()
           ^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/models/ffnn.py", line 57, in forward
    x = layer(x)
        ^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
    return inner()
           ^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (6373x1 and 6373x64)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/scripts/train_script.py", line 69, in main
    trainer = ModularTaskTrainer(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/trianand/local-work/thesis/autrainer/autrainer/training/training.py", line 157, in __init__
    self.bookkeeping.save_model_summary(
  File "/home/trianand/local-work/thesis/autrainer/autrainer/core/utils/bookkeeping.py", line 124, in save_model_summary
    s = summary(
        ^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torchinfo/torchinfo.py", line 223, in summary
    summary_list = forward_pass(
                   ^^^^^^^^^^^^^
  File "/home/trianand/local-work/HearTheSpecies/insectnet/insectnet-cnn10-v1/.devenv/state/venv/lib/python3.11/site-packages/torchinfo/torchinfo.py", line 304, in forward_pass
    raise RuntimeError(
RuntimeError: Failed to run torchinfo. See above stack traces for more details. Executed layers up to: []

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

and here the config for the model

```yaml
id: FFNN-IS16
_target_: autrainer.models.FFNN
input_size: 6373
hidden_size: 64
num_layers: 3
dropout: 0.5

transform:
  type: tabular
```

I mark it as question, as I am not sure if it's a bug yet, as I may have messed something up

**Comment by ramppdev** [comment]
Yeah makes sense that it doesnt work, as the expected input shape would be `(batch_size, input_size)` in the first layer of the `FFNN`.
This essentially is a bug as we dont expect an unnecessary dimension here, this is also wrong in the tests i wrote:
https://github.com/autrainer/autrainer/blob/b845ce6461805e5490dae1931f160b720d5241e0/tests/test_transforms.py#L325-L334

Just to confirm again, we correctly receive a 2D tensor of the LLDs (_without_ functionals), as they are calculated across the sample in a sliding window fashion.
But _with_ functionals, these should be calculated as global statistics, meaning we would expect a 1D tensor correct?

If this is true, yes, thats a bug and we need to squeeze the dimension in the `OpenSMILE` transform and fix the tests. I will do so.

**Comment by ATriantafyllopoulos** [comment]
Thanks, yes, precisely, this last dimension needs to go, but where does it come from? is it from `smile` itself?

**Comment by ramppdev** [comment]
> Thanks, yes, precisely, this last dimension needs to go, but where does it come from? is it from `smile` itself?
> 
> It appears to be:
> 
> ```python
> >>>import opensmile
> >>> import numpy as np
> >>> smile = opensmile.Smile()
> >>> smile.process_signal(np.random.rand(16000), 16000).to_numpy().shape
> (1, 6373)
> >>> smile.process_signal(np.random.rand(1, 16000), 16000).to_numpy().shape
> (1, 6373)
> ```

Yes, directly from opensmile. I will open a PR real quick.

**Comment by ATriantafyllopoulos** [comment]
I think there's also an interaction with the `if self.standardize` branch in `AIBO`, which should then be adapted to `torch.stack` (should hopefully show up in the tests)

**Comment by ramppdev** [comment]
> I think there's also an interaction with the `if self.standardize` branch in `AIBO`, which should then be adapted to `torch.stack` (should hopefully show up in the tests)

If there is one, this will probably not show up in the tests, we should open a new issue for it then.
